# Generated by Django 5.0.1 on 2024-06-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllIPs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(max_length=200)),
                ('ip_type', models.CharField(max_length=100)),
                ('path', models.CharField(blank=True, max_length=500, null=True)),
                ('sec_ch_ua', models.CharField(blank=True, max_length=500, null=True)),
                ('platform', models.CharField(blank=True, max_length=500, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('lang', models.CharField(blank=True, max_length=500, null=True)),
                ('comp_name', models.CharField(blank=True, max_length=500, null=True)),
                ('cpu_architecture', models.CharField(blank=True, max_length=500, null=True)),
                ('cpu_identifier', models.CharField(blank=True, max_length=500, null=True)),
                ('cpu_level', models.CharField(blank=True, max_length=500, null=True)),
                ('method', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
